version = 0.1

[default.global.parameters]
stack_name = "cloudshortener-dev"
region = "eu-central-1"

[default.build.parameters]
cached = true
parallel = true
use_container = true
template_file = "infra/template.yaml"

[default.validate.parameters]
lint = true
template_file = "infra/template.yaml"

[default.deploy.parameters]
capabilities = "CAPABILITY_IAM CAPABILITY_AUTO_EXPAND"
confirm_changeset = true

[default.package]
parameters = { }

[default.sync.parameters]
watch = false
stack_name = "cloudshortener-dev"
dependency_layer = false
code = true
use_container = true

[default.local_start_api.parameters]
warm_containers = "EAGER"

[default.local_start_lambda.parameters]
warm_containers = "EAGER"
