params:
  redis:
    host: redis-15602.crce198.eu-central-1-3.ec2.redns.redis-cloud.com
    port: 15602
    db: 0

secrets:
  redis:
    username: default
    password: LnKdNQtFOGIBmqdXAsuxifUlknqQ0APY
