# .github/workflows/unit_tests.yml
name: Run Python unit tests

on:
  workflow_call:
    inputs:
      python-version:
        type: string
        required: false
        default: '3.13'
      coverage-threshold:
        type: number
        required: false
        default: 80
      workdir:
        type: string
        required: false
        default: '.'
    secrets: {}  # keep empty unless you really need secrets here

permissions:
  contents: read

jobs:
  test:
    runs-on: ubuntu-latest
    # Only allow calls from *your* account and this repo
    # if: ${{ github.repository_owner_id == 24678930 && github.repository == 'Pejo-306/cloud-url-shortener' }}
    defaults:
      run:
        working-directory: ${{ inputs.workdir }}
    steps:
      - name: Checkout repository code
        uses: actions/checkout@v4

      - name: Set up uv
        uses: astral-sh/setup-uv@v4
        with:
          python-version: ${{ inputs['python-version'] }}
          enable-cache: true
          cache-dependency-glob: |
            backend/uv.lock
            backend/pyproject.toml

      - name: Install deps
        run: uv sync --frozen --directory backend

      - name: Run unit tests
        run: |
          set -uo pipefail
          uv run --directory backend pytest tests/unit \
            --cov=cloudshortener \
            --cov-report=html \
            --cov-report=term-missing \
            --cov-fail-under="${{ inputs.coverage-threshold }}" |& tee pytest.out
          ec=${PIPESTATUS[0]}; grep -E 'Required test coverage.*Total coverage:' pytest.out || true; exit $ec

      - name: Upload coverage html
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: coverage-html
          path: backend/htmlcov/
          retention-days: 7
